version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    environment:
      - LOG_PATH=/app/logs/logs.csv

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:5000/predict
    depends_on:
      - backend
